In [58]:
from sklearn.svm import LinearSVC
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt 

iris = datasets.load_iris()

seto = iris.data[0:50] 
vers = iris.data[50:100]
virg = iris.data[100:150]

class_seto = iris.target[0:50]
class_vers = iris.target[50:100]
class_virg = iris.target[100:150]

x_org = np.concatenate((vers,virg))
y = np.concatenate((class_vers, class_virg))
x = np.ones((100,5))
x[:,:-1] = x_org

#initialize w and b using least squares 

xt = x.T
sum1 = 0 #xTx
sum2 = 0 #yx
sum3 = 0 #y*xTx 

for i in range(0,100): 
    prod = np.matmul(x[i], x[i].T)
    sum1 = sum1 + prod

for i in range(0,100): 
    prod = y[i]*x[i]
    sum2 = sum2 + prod

for i in range(0,100): 
    prod = y[i]*np.matmul(x[i], x[i].T)
    sum3 = sum1 + prod

w = sum2/sum1

#Linear SVM 
E_old = 1
C = 1
epsilon = 10e-9

#Create lambda 
lam = np.identity(4)
lam = np.append(lam,np.zeros([len(lam),1]),1)
val = [[0,0,0,0,0]]
lam = np.vstack([lam,val])

#Energy Function 
u = 1

sec_term = 0 
sum4 = 0
for i in range(0,100): 
    prod = y[i]*np.matmul(w,x[i].T)
    prod = 1 - prod 
    prod = prod + u
    prod = (prod**2)/(4*u_i)
    sec_term = sec_term + prod

E = (0.5)*(w.T)*lam*w + sec_term


epochs = 0
while np.allclose(E_old,E,1e-5) == False: 
    epochs = epochs+1
    E_old = E 
    minval = abs(1 - y[0]*(np.matmul(w,x[0].T)))
    for i in range (1,100):
        u = abs(1 - y[i]*(np.matmul(w,x[i].T)))
        if u < epsilon: 
            minval = epsilon
            break 
        else: 
            if (u < minval):
                minval = u
                continue 
            else: 
                continue
    u = minval 
    K = (C/(2*u))*sum1
    v = ((C*(1+u))/(2*u))*sum2 
    w = ((lam+K)**-1)*v

print(w)
print(epochs)


29183.532601697
[[0.14089698 0.06427281 0.11326995 0.03964891 0.02211728]
 [0.14090181 0.06427061 0.11326995 0.03964891 0.02211728]
 [0.14090181 0.06427281 0.11326607 0.03964891 0.02211728]
 [0.14090181 0.06427281 0.11326995 0.03964755 0.02211728]
 [0.14090181 0.06427281 0.11326995 0.03964891 0.02211728]]
1
